<?php
if(!defined('ABSPATH'))exit;
/** A small, task-first layer over the existing operational screens. */
final class AAIHB_ControlCenter {
 const IMPORTANCE='aaihb_site_importance';
 const POSTCHECK='aaihb_recovery_postcheck';
 public static function boot(){
  add_action('admin_menu',function(){
   foreach(['aaihb-protect'=>'守る','aaihb-respond'=>'対応する','aaihb-grow'=>'広げる','aaihb-emergency'=>'緊急モード'] as $slug=>$label)add_submenu_page('aaihb-home',$label,$label,'manage_options',$slug,[__CLASS__,'page']);
  });
  add_action('admin_post_aaihb_control_center',[__CLASS__,'save']);
 }
 public static function importance($id){$all=get_option(self::IMPORTANCE,[]);return is_array($all)?($all[$id]??'normal'):'normal';}
 private static function form($op){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="aaihb_control_center"><input type="hidden" name="op" value="'.esc_attr($op).'">';wp_nonce_field('aaihb_control_center');}
 public static function save(){
  if(!current_user_can('manage_options'))wp_die('権限がありません。',403);check_admin_referer('aaihb_control_center');
  $op=sanitize_key($_POST['op']??'');
  if($op==='importance'){$id=sanitize_text_field(wp_unslash($_POST['id']??''));$level=sanitize_key($_POST['level']??'normal');if(AAIHB_Beta::site($id)&&in_array($level,['critical','normal','test'],true)){$all=get_option(self::IMPORTANCE,[]);if(!is_array($all))$all=[];$all[$id]=$level;update_option(self::IMPORTANCE,$all,false);$message='サイトの重要度を保存しました。';}else $message='保存できませんでした。';}
  elseif($op==='postcheck'){$checks=get_option(self::POSTCHECK,[]);if(!is_array($checks))$checks=[];foreach(['http','admin','database','email','form'] as $key)$checks[$key]=!empty($_POST[$key]);$checks['at']=gmdate('c');$checks['actor']=get_current_user_id();update_option(self::POSTCHECK,$checks,false);AAIHB_RecoveryEvidence::event('recovery_postcheck','','手動確認');$message='復旧後チェックを記録しました。';}
  elseif($op==='auto_postcheck'){
   global $wpdb;$auto=['at'=>gmdate('c'),'http'=>false,'admin'=>current_user_can('manage_options'),'database'=>false];
   $response=wp_remote_get(home_url('/'),['timeout'=>15,'redirection'=>3,'headers'=>['Cache-Control'=>'no-cache']]);
   $code=is_wp_error($response)?0:(int)wp_remote_retrieve_response_code($response);$auto['http']=$code>=200&&$code<300;$auto['http_code']=$code;
   $auto['database']=$wpdb->get_var('SELECT 1')==='1';
   $checks=get_option(self::POSTCHECK,[]);if(!is_array($checks))$checks=[];$checks['auto']=$auto;update_option(self::POSTCHECK,$checks,false);
   AAIHB_RecoveryEvidence::event('recovery_postcheck','','自動確認');$message='自動チェックを実行しました。メール・フォームは送信しないため、手動で確認してください。';
  }
  else $message='不明な操作です。';
  set_transient('aaihb_control_message_'.get_current_user_id(),$message,90);wp_safe_redirect(admin_url('admin.php?page='.($op==='importance'?'aaihb-grow':'aaihb-respond').'#postcheck'));exit;
 }
 private static function notice(){if($m=get_transient('aaihb_control_message_'.get_current_user_id())){echo '<div class="notice notice-info"><p>'.esc_html($m).'</p></div>';delete_transient('aaihb_control_message_'.get_current_user_id());}}
 private static function head($active,$title,$copy){echo '<div class="wrap aaihb-app aaihb-selfserve"><header class="ss-hero"><small>OPERATIONS CENTER</small><h1>'.esc_html($title).'</h1><p>'.esc_html($copy).'</p></header>';AAIHB_Dashboard::nav($active);self::notice();}
 public static function page(){AAIHB_Beta::allowed();$page=sanitize_key($_GET['page']??'');if($page==='aaihb-protect')self::protect();elseif($page==='aaihb-grow')self::grow();elseif($page==='aaihb-emergency')self::emergency();else self::respond();}
 public static function protect(){self::head('aaihb-protect','① 守る','バックアップ・復元テスト・更新前の安全確認をここにまとめます。');$g=AAIHB_RecoveryEvidence::gate();$tone=$g['state']==='ready'?'#16803c':($g['state']==='warning'?'#9a6700':'#b42318');$score=isset($g['latest']['score'])?(int)$g['latest']['score']['score']:0;echo '<section class="ss-card"><h2>更新リスク：<span style="color:'.esc_attr($tone).'">'.esc_html($g['state']==='ready'?'復元確認済み':($g['state']==='warning'?'再確認が必要':'未確認・失敗あり')).'</span></h2><p>'.esc_html($g['message']).'</p><p><strong>復元信頼度スコア：'.$score.' / 100</strong></p><p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=aaihb-vault#evidence')).'">復旧リハーサルを開始する</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-vault')).'">セーフティゲートを設定する</a></p></section><section class="ss-card"><h2>更新前後の変更記録</h2><p>WordPress・テーマ・プラグインの通常更新時に、対象と更新前後のバージョンを自動記録します。ファイル内容や秘密情報は保存しません。</p><table class="widefat striped"><thead><tr><th>日時（UTC）</th><th>対象</th><th>変更</th></tr></thead><tbody>';$changes=AAIHB_ChangeEvidence::latest();if(!$changes)echo '<tr><td colspan="3">まだ更新差分はありません。</td></tr>';foreach(array_slice($changes,0,10) as $c)echo '<tr><td>'.esc_html($c['at']).'</td><td>'.esc_html($c['type'].' / '.$c['target']).'</td><td>'.esc_html(($c['before']?:'不明').' → '.($c['after']?:'不明').($c['changed']?'':'（差分なし）')).'</td></tr>';echo '</tbody></table><p>障害が起きた場合は、ここで直前の変更を確認してから緊急モードへ進んでください。</p><a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-emergency')).'">緊急モードを開く</a></section></div>';}
 public static function emergency(){self::head('aaihb-emergency','緊急モード','障害時はメニューを探さず、上から順番に進めます。');echo '<section class="ss-card"><h2>異常を確認しました</h2><ol><li><strong>現在の状態を保存</strong><br><a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-vault')).'">保存ポイントを確認・作成する</a></li><li><strong>直前の保存ポイントを確認</strong><br>隔離復元テストの結果を見ます。</li><li><strong>本番復元を実行する</strong><br>同じ画面の手順に従い、対象と影響範囲を確認してから実行します。</li><li><strong>復旧後チェックを記録</strong><br><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=aaihb-respond#postcheck')).'">復旧後チェックへ進む</a></li></ol><p>購入処理・フォーム送信・外部連携は、隔離復元テストの確認対象外です。必要なものだけを復旧後チェックで実サイト確認してください。</p></section></div>';}
 public static function respond(){self::head('aaihb-respond','② 対応する','障害・更新・復旧履歴を、次に行う操作から確認します。');echo '<section class="ss-card"><h2>ワンクリック緊急モード</h2><p>障害時に必要な操作だけを大きく表示します。</p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=aaihb-emergency')).'">緊急モードを開く</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-ops')).'">障害・対応案件を見る</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-vault')).'">復旧履歴を見る</a></section><section id="postcheck" class="ss-card"><h2>復旧後の自動チェック</h2><p>トップページの HTTP 応答、現在の管理権限、DB接続を自動確認します。メールとフォームは送信しないため、下の手動確認で記録してください。</p>'; $last=get_option(self::POSTCHECK,[]);if(!is_array($last))$last=[];$auto=$last['auto']??[];echo '<p><strong>自動確認：</strong>'.(!empty($auto['at'])?esc_html($auto['at']).'（UTC）':'未実行').'<br>トップページ：'.(!empty($auto['http'])?'確認済み（HTTP '.(int)($auto['http_code']??0).'）':'未確認').' ／ 管理画面：'.(!empty($auto['admin'])?'確認済み':'未確認').' ／ DB：'.(!empty($auto['database'])?'確認済み':'未確認').'</p>';self::form('auto_postcheck');submit_button('復旧後の自動チェックを実行','secondary');echo '</form><hr><h3>手動で確認する項目</h3><p>「復元できた」だけで完了にせず、実サイトで必要な項目を確認して記録します。</p>';self::form('postcheck');foreach(['http'=>'トップページ（HTTP 200）','admin'=>'管理画面にログイン','database'=>'DBの表示・保存','email'=>'メール送信','form'=>'フォーム送信'] as $k=>$label)echo '<p><label><input type="checkbox" name="'.esc_attr($k).'" value="1" '.checked(!empty($last[$k]),true,false).'> '.esc_html($label).'</label></p>';submit_button('手動チェック結果を記録','primary');echo '</form><p>最終手動記録：'.esc_html($last['at']??'未記録').'</p></section></div>';}
 public static function grow(){self::head('aaihb-grow','③ 広げる','接続サイト・チーム・料金・顧客向け閲覧を管理します。');echo '<section class="ss-card"><h2>接続サイトと重要度</h2><p>重要サイトを先に見つけられるよう、「重要・通常・テスト」を設定します。</p><table class="widefat striped"><thead><tr><th>サイト</th><th>重要度</th><th>顧客向け閲覧</th></tr></thead><tbody>';foreach(AAIHB_Beta::sites() as $id=>$site){echo '<tr><td>'.esc_html($site['name']).'</td><td>';self::form('importance');echo '<input type="hidden" name="id" value="'.esc_attr($id).'"><select name="level">';foreach(['critical'=>'重要','normal'=>'通常','test'=>'テスト'] as $v=>$l)echo '<option value="'.esc_attr($v).'" '.selected(self::importance($id),$v,false).'>'.esc_html($l).'</option>';echo '</select> ';submit_button('保存','small secondary','submit',false);echo '</form></td><td><a class="button" target="_blank" rel="noopener" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=aaihb_report&site='.rawurlencode($id)),'aaihb_report')).'">結果だけを開く</a></td></tr>';}echo '</tbody></table><p>「結果だけを開く」は顧客向け報告書です。顧客に操作権限を渡さず、診断結果と対応状況だけを共有できます。</p></section><section class="ss-card"><h2>チーム・料金・接続</h2><a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-fleet')).'">グループ・予約</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-license')).'">利用数と料金</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=aaihb-start')).'">かんたん接続</a></section></div>';}
}
