<?php
if(!defined('ABSPATH'))exit;
/** Read-only product-verification status. An unavailable CI API is never a passing test. */
final class AAIHB_Verification {
 const CACHE='aaihb_verification_github';
 const REPO='masa45594-crypto/autorepair-central';
 public static function boot(){add_action('admin_menu',function(){add_submenu_page('aaihb-home','最新検証結果','最新検証結果','manage_options','aaihb-verification',[__CLASS__,'page']);});add_action('admin_post_aaihb_verification_refresh',[__CLASS__,'refresh']);}
 private static function api($path){$r=wp_remote_get('https://api.github.com/repos/'.self::REPO.$path,['timeout'=>8,'redirection'=>0,'headers'=>['Accept'=>'application/vnd.github+json','User-Agent'=>'AutoRepair-AI-Hosting-Beta']]);if(is_wp_error($r)||(int)wp_remote_retrieve_response_code($r)!==200)return null;$data=json_decode(wp_remote_retrieve_body($r),true);return is_array($data)?$data:null;}
 public static function remote($force=false){$cached=get_transient(self::CACHE);if(!$force&&is_array($cached))return $cached;$runs=self::api('/actions/workflows/356702858/runs?per_page=1');$run=is_array($runs)&&!empty($runs['workflow_runs'][0])?$runs['workflow_runs'][0]:null;$out=['available'=>false,'run'=>null,'jobs'=>[],'checked_at'=>gmdate('c')];if(is_array($run)&&!empty($run['id'])){$out['available']=true;$out['run']=['id'=>(int)$run['id'],'number'=>(int)($run['run_number']??0),'status'=>(string)($run['status']??''),'conclusion'=>(string)($run['conclusion']??''),'url'=>esc_url_raw($run['html_url']??'')];$jobs=self::api('/actions/runs/'.(int)$run['id'].'/jobs?per_page=20');foreach((array)($jobs['jobs']??[]) as $j)$out['jobs'][sanitize_key($j['name']??'')]=(string)($j['conclusion']??$j['status']??'');}set_transient(self::CACHE,$out,15*MINUTE_IN_SECONDS);return $out;}
 private static function job($remote,$name){return is_array($remote)&&($remote['jobs'][$name]??'')==='success';}
 public static function matrix($remote=null){if($remote===null)$remote=self::remote();$core=self::job($remote,'central');$unit=self::job($remote,'unit');$restore=self::job($remote,'restore');$stripe=self::job($remote,'stripe');$ok=function($yes){return $yes?'passed':'unknown';};return [
 ['key'=>'install','label'=>'新規インストール','detail'=>'有効化後にエラーなし','state'=>$ok($unit&&$restore),'scope'=>'WordPress契約テスト・隔離Docker環境'],
 ['key'=>'upgrade','label'=>'旧版からの更新','detail'=>'0.15.0 から最新版へ更新し、登録データを維持','state'=>$ok($restore),'scope'=>'隔離Docker環境'],
 ['key'=>'backup','label'=>'バックアップ','detail'=>'ファイル・DB の保存完了','state'=>$ok($restore),'scope'=>'隔離Docker環境'],
 ['key'=>'corrupt','label'=>'破損バックアップ拒否','detail'=>'壊れたアーカイブを復元不可にする','state'=>$ok($restore),'scope'=>'隔離Docker環境'],
 ['key'=>'restore','label'=>'バックアップ・復元','detail'=>'DB・トップページ・WordPress 起動を確認','state'=>$ok($restore),'scope'=>'隔離Docker環境'],
 ['key'=>'rollback','label'=>'更新ロールバック','detail'=>'壊したプラグイン更新から戻せる','state'=>$ok($restore),'scope'=>'隔離Docker環境'],
 ['key'=>'central','label'=>'中央サーバー API','detail'=>'認証・計量・重複イベント拒否・解約停止','state'=>$ok($core),'scope'=>'Python自動テスト'],
 ['key'=>'stripe','label'=>'Stripe Webhook','detail'=>'重複受信・署名・解約後の停止を確認','state'=>$stripe?'passed':'pending','scope'=>$stripe?'Stripeテストモード':'テスト用シークレット設定後に実行'],
 ['key'=>'paddle','label'=>'Paddle 連携','detail'=>'Webhookの重複受信と解約停止','state'=>'preparing','scope'=>'連携方針の準備中'],
 ['key'=>'load','label'=>'大量サイト利用数同期','detail'=>'100・500・1,000サイト相当を測定','state'=>(($remote['jobs']['load']??'')==='success'?'passed':'pending'),'scope'=>'手動の負荷計測ワークフロー'],
 ['key'=>'permission','label'=>'権限','detail'=>'一般ユーザーは復元・契約設定を実行不可','state'=>$ok($unit),'scope'=>'WordPress契約テスト'],
 ];}
 public static function summary($remote=null){$m=self::matrix($remote);$out=['passed'=>0,'pending'=>0,'preparing'=>0,'unknown'=>0];foreach($m as $r)$out[$r['state']]++;return $out;}
 public static function refresh(){if(!current_user_can('manage_options'))wp_die('権限がありません。',403);check_admin_referer('aaihb_verification_refresh');delete_transient(self::CACHE);self::remote(true);wp_safe_redirect(admin_url('admin.php?page=aaihb-verification'));exit;}
 public static function badge($state){return ['passed'=>'✓ 確認済み','pending'=>'△ 未検証','preparing'=>'○ 準備中','unknown'=>'? 取得待ち'][$state]??'? 不明';}
 private static function form(){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="aaihb_verification_refresh">';wp_nonce_field('aaihb_verification_refresh');}
 public static function page(){AAIHB_Beta::allowed();$remote=self::remote();$sum=self::summary($remote);echo '<div class="wrap aaihb-app aaihb-selfserve"><header class="ss-hero"><small>PRODUCT VERIFICATION</small><h1>最新検証結果</h1><p>何が自動確認済みで、何が未検証かを導入者にも分かる形で表示します。</p></header>';AAIHB_Dashboard::nav('aaihb-verification');echo '<section class="ss-card"><h2>GitHub Actions</h2>';if($remote['available']&&$remote['run']){echo '<p><strong>実行 #'.(int)$remote['run']['number'].'：</strong> '.esc_html($remote['run']['conclusion']==='success'?'成功':($remote['run']['conclusion']?:'実行中')).' ／ 最終取得 '.esc_html($remote['checked_at']).'</p>';if($remote['run']['url'])echo '<p><a class="button" target="_blank" rel="noopener" href="'.esc_url($remote['run']['url']).'">GitHub Actionsを開く</a></p>';}else echo '<p>GitHub Actionsの最新結果を取得できませんでした。未取得の結果は「確認済み」として扱いません。</p>';self::form();submit_button('最新結果を再取得','secondary');echo '</form></section>';echo '<section class="ss-card"><h2>検証の内訳</h2><p>確認済み '.(int)$sum['passed'].'件 ／ 未検証 '.(int)$sum['pending'].'件 ／ 準備中 '.(int)$sum['preparing'].'件 ／ 取得待ち '.(int)$sum['unknown'].'件</p><table class="widefat striped"><thead><tr><th>項目</th><th>結果</th><th>合格条件</th><th>検証範囲</th></tr></thead><tbody>';foreach(self::matrix($remote) as $r)echo '<tr><td>'.esc_html($r['label']).'</td><td><strong class="aaihb-verify-'.esc_attr($r['state']).'">'.esc_html(self::badge($r['state'])).'</strong></td><td>'.esc_html($r['detail']).'</td><td>'.esc_html($r['scope']).'</td></tr>';echo '</tbody></table><p>「確認済み」は直近のGitHub Actionsが成功した範囲です。本番サイト、本番課金、外部サービスの実運用を保証するものではありません。</p></section></div>';}
}
