<?php
if(!defined('AAIHB_TESTING')||!AAIHB_TESTING)exit;
require_once ABSPATH.'wp-admin/includes/plugin.php';require_once ABSPATH.'wp-admin/includes/template.php';wp_set_current_user(1);activate_plugin('autorepair-ai-hosting-beta/autorepair-ai-hosting-beta.php');AAIHB_Beta::upgrade();do_action('init');
$n=0;function rcheck($x,$label){global $n;if(!$x)throw new RuntimeException('FAIL '.$label);$n++;echo "PASS $label\n";}function rreject($f,$label){try{$f();}catch(RuntimeException $e){rcheck(true,$label);return;}rcheck(false,$label);}
rcheck(!class_exists('WPAI_Diagnostics'),'no core dependency');rcheck(!get_option('aaihb_recovery_auto',false),'automation default off');
update_option('permalink_structure','/%postname%/');global $wp_rewrite;$wp_rewrite->init();update_option('rewrite_rules',['before'=>'value']);$id=AAIHB_Recovery::repair('rules');$d=AAIHB_Recovery::data($id);rcheck($d['before']['value']===['before'=>'value'],'pre-change rules saved');rcheck($d['state']==='applied','repair applied');rcheck(get_option('rewrite_rules')!==['before'=>'value'],'rules actually rebuilt');AAIHB_Recovery::restore($id);rcheck(get_option('rewrite_rules')===['before'=>'value'],'rules restored');rreject(function()use($id){AAIHB_Recovery::restore($id);},'repeat restore refused');
$id=AAIHB_Recovery::repair('rules');update_option('rewrite_rules',['new'=>'other']);rreject(function()use($id){AAIHB_Recovery::restore($id);},'later changes preserved');rcheck(get_option('rewrite_rules')===['new'=>'other'],'conflict not overwritten');
$file=ABSPATH.'.maintenance';$text='<?php $upgrading = '.(time()-4000).';';file_put_contents($file,$text);$id=AAIHB_Recovery::repair('maintenance');rcheck(!file_exists($file),'stale file removed');AAIHB_Recovery::restore($id);rcheck(file_get_contents($file)===$text,'exact maintenance bytes restored');unlink($file);
file_put_contents($file,'<?php $upgrading = '.time().';');rreject(function(){AAIHB_Recovery::repair('maintenance');},'active maintenance refused');unlink($file);file_put_contents($file,'<?php echo "custom";');rreject(function(){AAIHB_Recovery::repair('maintenance');},'nonstandard PHP refused');unlink($file);
file_put_contents($file,$text);update_option('core_updater.lock',time());rreject(function(){AAIHB_Recovery::repair('maintenance');},'updater lock respected');delete_option('core_updater.lock');unlink($file);
rreject(function(){AAIHB_Recovery::repair('arbitrary');},'allowlist enforced');
delete_option('rewrite_rules');update_option('aaihb_recovery_auto',true);AAIHB_Recovery::tick();rcheck(is_array(get_option('rewrite_rules'))&&get_option('rewrite_rules'),'automatic repair runs');$last=get_option('aaihb_recovery_last');delete_option('rewrite_rules');AAIHB_Recovery::tick();rcheck(get_option('rewrite_rules',null)===null,'daily limit respected');
add_option('aaihb_recovery_lock',time(),'',false);rreject(function(){AAIHB_Recovery::repair('rules');},'concurrent repair rejected');delete_option('aaihb_recovery_lock');
$_GET=['page'=>'aaihb-recovery'];ob_start();AAIHB_Recovery::page();$h=ob_get_clean();file_put_contents('/qa/recovery-page.html',$h);rcheck(strpos($h,'自動修復')!==false,'repair UI renders');
add_filter('wp_die_handler',function(){return function(){throw new RuntimeException('Denied');};});$_REQUEST=[];rreject(function(){AAIHB_Recovery::save();},'CSRF rejected');wp_set_current_user(wp_create_user('repair_reader','test-only-pass'));rreject(function(){AAIHB_Recovery::page();},'subscriber denied');
echo "TOTAL $n checks passed\n";
