<?php
if(!defined('AAIHB_TESTING'))exit;
require_once ABSPATH.'wp-admin/includes/plugin.php';require_once ABSPATH.'wp-admin/includes/template.php';wp_set_current_user(1);require_once '/wordpress/wp-content/plugins/autorepair-ai-hosting-beta/autorepair-ai-hosting-beta.php';AAIHB_Beta::upgrade();
$n=0;function vcheck($v,$s){global $n;if(!$v)throw new RuntimeException('FAIL '.$s);$n++;echo "PASS $s\n";}function vreject($f,$s){try{$f();}catch(RuntimeException $e){vcheck(true,$s);return;}vcheck(false,$s);}
mkdir('/private-vault',0700);chmod('/private-vault',0700);define('AAIHB_VAULT_DIR','/private-vault');define('AAIHB_PUBLIC_ROOT','/wordpress');
vcheck(!class_exists('WPAI_Backups'),'independent from AutoRepair core');vcheck(!get_option('aaihb_guard_enabled'),'guard defaults off');vcheck(class_exists('ZipArchive'),'ZipArchive available');
$root=WP_PLUGIN_DIR.'/vault-fixture';mkdir($root);file_put_contents($root.'/fixture.php','<?php /* Plugin Name: Vault Fixture */ // v1');mkdir($root.'/nested');file_put_contents($root.'/nested/data.bin',"\0\xffDATA");
$id=AAIHB_PluginGuard::snapshot('vault-fixture/fixture.php');[$dir,$d]=AAIHB_VaultIO::point($id);vcheck($d['kind']==='plugin','signed snapshot ready');file_put_contents($root.'/fixture.php','<?php // v2');$work=AAIHB_PluginGuard::restore($id);vcheck(strpos(file_get_contents($root.'/fixture.php'),'v1')!==false,'plugin bytes restored');vcheck(strpos(file_get_contents(AAIHB_VAULT_DIR.'/'.$work.'/previous/fixture.php'),'v2')!==false,'pre-restore files retained');vcheck(file_get_contents($root.'/nested/data.bin')==="\0\xffDATA",'binary file restored');
unlink($root.'/fixture.php');AAIHB_PluginGuard::restore($id);vcheck(is_file($root.'/fixture.php'),'missing main plugin file restored');
$expected=AAIHB_VaultIO::inventory($root);file_put_contents($root.'/later','change');vreject(function()use($id,$expected){AAIHB_PluginGuard::restore($id,$expected);},'later changes block automatic restore');unlink($root.'/later');
vreject(function(){AAIHB_PluginGuard::target('../bad/main.php');},'path traversal rejected');vreject(function(){AAIHB_PluginGuard::target('autorepair-ai-hosting-beta/autorepair-ai-hosting-beta.php');},'self rollback rejected');vreject(function(){AAIHB_PluginGuard::target('hello.php');},'single-file rollback rejected');
$lock=AAIHB_VaultIO::lock();vreject(function(){AAIHB_PluginGuard::snapshot('vault-fixture/fixture.php');},'concurrent backup rejected');AAIHB_VaultIO::unlock($lock);
file_put_contents($dir.'/manifest.json','tampered');vreject(function()use($id){AAIHB_VaultIO::point($id);},'manifest tampering rejected');
$id=AAIHB_PluginGuard::snapshot('vault-fixture/fixture.php');[$dir,$d]=AAIHB_VaultIO::point($id);file_put_contents($dir.'/files.zip','broken');vreject(function()use($id){AAIHB_VaultIO::point($id);},'payload corruption rejected');
update_option('aaihb_guard_enabled',true);$codes=[200,503,503];add_filter('pre_http_request',function()use(&$codes){$c=array_shift($codes)??200;return ['headers'=>[],'body'=>'','response'=>['code'=>$c,'message'=>'fixture'],'cookies'=>[]];});
vcheck(AAIHB_PluginGuard::before(true,['plugin'=>'vault-fixture/fixture.php'])===true,'update allowed after successful backup');file_put_contents($root.'/fixture.php','<?php // broken v3');AAIHB_PluginGuard::after(null,['type'=>'plugin','action'=>'update','plugins'=>['vault-fixture/fixture.php']]);vcheck(strpos(file_get_contents($root.'/fixture.php'),'v1')!==false,'two 5xx trigger rollback');
$codes=[200,0];AAIHB_PluginGuard::before(true,['plugin'=>'vault-fixture/fixture.php']);file_put_contents($root.'/fixture.php','<?php // v4');AAIHB_PluginGuard::after(null,['type'=>'plugin','action'=>'update','plugins'=>['vault-fixture/fixture.php']]);vcheck(strpos(file_get_contents($root.'/fixture.php'),'v4')!==false,'unknown HTTP does not trigger rollback');
vcheck(is_wp_error(AAIHB_PluginGuard::before(true,['plugin'=>'hello.php'])),'unsupported protected update blocked');
ob_start();AAIHB_VaultAdmin::page();$html=ob_get_clean();file_put_contents('/qa/vault-page.html',$html);vcheck(strpos($html,'バックアップ')!==false,'admin screen renders');
add_filter('wp_die_handler',function(){return function(){throw new RuntimeException('Denied');};});$_REQUEST=[];vreject(function(){AAIHB_VaultAdmin::save();},'nonce required');wp_set_current_user(wp_create_user('vault-reader','only-for-test'));vreject(function(){AAIHB_VaultAdmin::save();},'nonadmin mutation denied');
echo "TOTAL $n checks passed\n";
